### ISSUE TITLE
Mac版运行不了

### ISSUE THREAD

**Issue by shenfu1991** [clangcn/kcp-server#1]
windows正常运行，能否看下什么原因，直接运行提示permission denied ,加了权限之后提示“invalid character '\n' in string literal”，谢谢。

**Comment by clangcn** [comment]
我的osx 10.11.5运行正常，看看是不是程序下载不完整，重新下载一下试试

**Comment by clangcn** [comment]
latest中的client_darwin_amd64我在osx10.11.5中可以正常运行，重新下载试试。
