### ISSUE TITLE
少年本地端怎么配置呀？

### ISSUE THREAD

**Issue by wangweichang** [clangcn/kcp-server#10]
我一打开就是这样
2016/07/22 19:44:32 version: 20160720
2016/07/22 19:44:32 communication mode: fast
2016/07/22 19:44:32 encryption: aes
2016/07/22 19:44:32 nodelay parameters: 0 20 2 1
2016/07/22 19:44:32 sndwnd: 128 rcvwnd: 1024
2016/07/22 19:44:32 acknodelay: false
2016/07/22 19:44:32 dscp: 0
2016/07/22 19:44:32 compression: true
2016/07/22 19:44:32 datashard: 10 parityshard: 3
2016/07/22 19:44:32 remote address: vps:29900
2016/07/22 19:44:32 listening socks5 on: [::]:12948
然后。。。。软件就自己关掉了

**Comment by wangweichang** [comment]
c:\1>client_windows_amd64.exe -c client.json
2016/07/22 20:00:09 version: 20160720
2016/07/22 20:00:09 communication mode: fast2
2016/07/22 20:00:09 encryption: aes
2016/07/22 20:00:09 nodelay parameters: 1 20 2 1
2016/07/22 20:00:09 sndwnd: 128 rcvwnd: 1024
2016/07/22 20:00:09 acknodelay: false
2016/07/22 20:00:09 dscp: 0
2016/07/22 20:00:09 compression: true
2016/07/22 20:00:09 datashard: 10 parityshard: 3
2016/07/22 20:00:09 remote address: 172._**.__.48:_**
2016/07/22 20:00:09 listening socks5 on: [::]:1080
2016/07/22 20:01:09 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/22 20:01:09 [ERR] yamux: Failed to read header: broken pipe

**Comment by wangweichang** [comment]
上面的端口占用我解决了。。。最新一条是这样的
2016/07/22 20:05:22 socks handshake: socks version not supported
2016/07/22 20:05:22 closed addr
2016/07/22 20:05:23 socks handshake: socks version not supported
2016/07/22 20:05:23 closed addr
2016/07/22 20:05:25 socks handshake: socks version not supported
2016/07/22 20:05:25 closed addr
2016/07/22 20:05:26 socks handshake: socks version not supported
2016/07/22 20:05:26 closed addr

**Comment by clangcn** [comment]
{
    "server":"You VPS IP",
    "server_port":8089,
    "password":"YouKcpPassword",
    "socks5_port":1080,
    "redir_port":0,
    "nocomp": false,
    "sndwnd":128,
    "rcvwnd":1024,
    "mtu":1350,
    "mode":"fast2"
}

**Comment by clangcn** [comment]
close
