### ISSUE TITLE
长时间运行会连不上？以及start failed问题。

### ISSUE THREAD

**Issue by ShikiYuki** [clangcn/kcp-server#14]
两个vps，一个是vultr的debian 8 x64，一个是DO的debian 8.5 32bit
都是最便宜的配置
config是
{
    "server":"0.0.0.0",
    "redir_port":0,
    "mode":"fast2",
    "sndwnd":128,
    "rcvwnd":1024,
    "mtu":1350,
    "nocomp": false,
    "port_password":
    {
        "554": "YouKcpPassword"
    },
    "_comment":
    {
        "554": "The server port comment"
    }
}
这样的
家里是联通网络

先说DO的那边

前天装上运行良好，今晚下班回家看了几个油管视频后发现连不上了，restart之后能连上一阵子之后又不行了
ssh上去，先stop了，在config里面加了一行端口和密码
    {
        "554": "YouKcpPassword"
        "**_": "**__"
    },
    "_comment":
    {
        "554": "The server port comment"
        "_**": "*******"
    }
这样，然后/etc/init.d/kcp-server start
提示Starting kcp-server...start failed

./install-kcp-server.sh uninstall
完了再install，能用一阵子
然后又不行
再尝试改config，又start failed了

然后我就来发帖了

Vultr那边……昨天才装上的，速度比DO的慢点，但是比之前用SS好不少
今晚也发现连不上了
还没折腾，就来发帖了……

**Comment by ShikiYuki** [comment]
更新：这回在折腾前把DO那台的config备份过，改了以后启动不能然后替换回去，又能启动了

所以这个kcp-server如果多人连一个端口是否可行？如果要多用户的话，具体应该如何更改config？

**Comment by clangcn** [comment]
多用户配置每个端口后面要有逗号，只有最后一个不能有逗号，参考我的多端口配置文件：

```
{
    "server":"0.0.0.0",
    "redir_port":0,
    "mode":"fast2",
    "sndwnd":128,
    "rcvwnd":1024,
    "mtu":1350,
    "nocomp": false,
    "port_password":
    {
        "8089": "YouKcpPassword1",
        "8090": "YouKcpPassword2",
        "8091": "YouKcpPassword3"
    },
    "_comment":
    {
        "8089": "Me",
        "8090": "Zhangsan",
        "8091": "Lisi"
    }
}
```

**Comment by ShikiYuki** [comment]
多谢，现在多用户配置正常了

ps:在vultr的服务器上测试OK，在DO的vps上多用户还是会failed，改回单用户配置就正常，和系统有关系吗？
