### ISSUE TITLE
 "端口1": "密码1"是填shadowsocks配置文件里的端口密码吗？

### ISSUE THREAD

**Issue by eee-du** [clangcn/kcp-server#15]
"端口1": "密码1"是填shadowsocks配置文件里的端口密码吗？

**Comment by clangcn** [comment]
"端口1": "密码1"是kcp自己的端口，kcp-server和shadowsocks是两个独立的程序，端口不能冲突

**Comment by eee-du** [comment]
@clangcn mac客户端运行显示 dscp: setsockopt: invalid argument
