### ISSUE TITLE
如果要配置配合SS是用如何写配置文件?

### ISSUE THREAD

**Issue by fudingyu** [clangcn/kcp-server#18]
sudo kcptun -l :53 -t 127.0.0.1:8388

这里面的-t就是target server address，请问在配置文件中如何写？

**Comment by clangcn** [comment]
需要使用原版，原版的一键安装脚本：
https://raw.githubusercontent.com/clangcn/kcp-server/master/install-kcptun.sh

**Comment by fudingyu** [comment]
哦，修改之后的KCP Server没有这个功能？

**Comment by clangcn** [comment]
恩，暂时没支持-t这个参数
