### ISSUE TITLE
0812版本无法连接

### ISSUE THREAD

**Issue by yyysuo** [clangcn/kcp-server#19]
0812版本，全部无法连接了。kcp-server程序由0728版本的1M多到了3M多。

**Comment by loveuall** [comment]
我看作者以前的脚本，有 upx 压缩。但有的地方 upx 压缩会运行失败。可能作者去掉压缩了。

无法连接请再更新下，我更新，现在是可以连接的。刚刚又更新并测试过了。

**Comment by loveuall** [comment]
arm5 arm7 在路由器上是保持压缩的二进制，所以还是 1M，节省路由器空间。

**Comment by clangcn** [comment]
刚开始编译的版本存在小bug，重新编译了，请使用脚本更新客户端，
`./install-kcp-server.sh update`
至于体积问题，之前的版本使用upx压缩了，但是从本次更新开始，部分服务器端和客户端使用upx压缩后无法使用，所以很多都没有压缩，所以看大小是3M左右，不影响使用。
