### ISSUE TITLE
跟官方有什么差别？

### ISSUE THREAD

**Issue by sarielKings** [clangcn/kcp-server#22]
问一下，这个跟官方有什么差别？我用过官方的，kcptun+ss没有成功，但是用你这个就没问题，如果可以，希望解答一下，先说一声谢谢。

**Comment by clangcn** [comment]
你用的哪个一键脚本？install-kcptun.sh这个就是安装官方的，官方的kcptun需要配合$$才能实现科学上网，kcp-server是在kcptun基础上再次开发的，自身就可以实现科学上网，不需要和$$配合，主要用于路由器上使用
