### ISSUE TITLE
原版客户端连不上

### ISSUE THREAD

**Issue by tooodooo** [clangcn/kcp-server#23]
都是最新版，在MAC上用原版的客户端连不上，如何解决？谢谢

**Comment by clangcn** [comment]
设置问题，我mac上测试可以正常使用，仔细查看两端配置，方便的话可以把你两端的配置发上来看看，主意隐藏服务器IP、端口、密码等重要信息。

**Comment by tooodooo** [comment]
client.json:

```
{
    "localaddr": ":12948",
    "remoteaddr": "xxx.xxx.xxx.xxx:9090",
    "key": "xxx",
    "crypt": "aes-128",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 128,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}
```

server-kcptun.json:

```
{
    "listen": ":9090",
    "target": "127.0.0.1:12948",
    "key": "xxx",
    "crypt": "aes-128",
    "mode": "fast2",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}
```

MAC客户端使用原版20160906版本

$ ./client_darwin_amd64 -c client.json 
2016/09/07 12:45:05 version: 20160906
2016/09/07 12:45:05 listening on: [::]:12948
2016/09/07 12:45:05 encryption: aes-128
2016/09/07 12:45:05 nodelay parameters: 1 20 2 1
2016/09/07 12:45:05 remote address: xxx.xxx.xxx.xxx:9090
2016/09/07 12:45:05 sndwnd: 128 rcvwnd: 1024
2016/09/07 12:45:05 compression: true
2016/09/07 12:45:05 mtu: 1350
2016/09/07 12:45:05 datashard: 70 parityshard: 30
2016/09/07 12:45:05 acknodelay: false
2016/09/07 12:45:05 dscp: 46
2016/09/07 12:45:05 sockbuf: 4194304
2016/09/07 12:45:05 keepalive: 10
2016/09/07 12:45:05 conn: 1
2016/09/07 12:45:05 autoexpire: 60

分别测试了网络代理和SS客户端都无法连接

**Comment by r03r03** [comment]
是不是两个端口弄反了

**Comment by tooodooo** [comment]
没有，客户端监听的默认12948端口，转发到服务器的9090，服务器端监听的9090，转发到socks5的默认12948

**Comment by clangcn** [comment]
更新下服务器端和客户端，修正了之前的小bug，如果还有问题可以留下留下邮箱，我把我qq发给你远程帮你看看

**Comment by tooodooo** [comment]
服务端更新了。
这是用了你刚提交的客户端连接信息：

2016/09/07 20:52:39 version: 20160907  
2016/09/07 20:52:39 listening on: [::]:62515  //客户端配置的监听端口没起作用，用默认的1082是可以的，我配置的是12948，启动就会随机端口号
2016/09/07 20:52:39 encryption: aes-128
2016/09/07 20:52:39 nodelay parameters: 1 20 2 1
2016/09/07 20:52:39 remote address: xxx.xxx.xxx.xxx:9090
2016/09/07 20:52:39 sndwnd: 128 rcvwnd: 1024
2016/09/07 20:52:39 compression: true
2016/09/07 20:52:39 mtu: 1350
2016/09/07 20:52:39 datashard: 70 parityshard: 30
2016/09/07 20:52:39 acknodelay: false
2016/09/07 20:52:39 dscp: 46
2016/09/07 20:52:39 sockbuf: 4194304
2016/09/07 20:52:39 keepalive: 10
2016/09/07 20:52:39 conn: 1
2016/09/07 20:52:39 autoexpire: 60
2016/09/07 20:52:39 redir: 
2016/09/07 20:54:10 socks handshake: socks version not supported
2016/09/07 20:54:10 closed addr 

修改了SS客户端的端口62515，socks版本不支持
配置了当前网络的代理也是报这个错误

我的邮箱：bg4gtw@qq.com

谢谢：）

**Comment by clangcn** [comment]
客户端改成ss，服务器上也得改成ss，
