### ISSUE TITLE
VPS与电脑端都同时安装了kcptun和kcp-server，kcp-server报错。

### ISSUE THREAD

**Issue by yyysuo** [clangcn/kcp-server#24]
Usage: ./socks5 0.0.0.0:12948 12948是kcptun在pc端的本地端口。

**Comment by clangcn** [comment]
没看懂

**Comment by loveuall** [comment]
https://github.com/clangcn/kcp-server/issues/26

请作者改用 127.0.0.1:12948 这样会比较安全。
