### ISSUE TITLE
sock5程序是干什么用的？

### ISSUE THREAD

**Issue by zhangminghao1989** [clangcn/kcp-server#26]
sock5程序是干什么用的？

**Comment by zhangminghao1989** [comment]
看了一下init脚本，这个应该是提供一个公共socks5代理的吧？没有密码验证的代理很危险，请不要随意安装额外的程序。

**Comment by loveuall** [comment]
socks5 源代码：
https://github.com/loveuall/kcptun/blob/router/socks5/main.go

确实，开放端口很危险，应该使用 127.0.0.1:12948 这样的配置。

**Comment by clangcn** [comment]
感谢反馈，不好意思，我代码写的不够严谨，直接使用脚本更新或者修改init文件中的0.0.0.0为127.0.0.1，这样就不会变成公共socks5代理了。至于说的不要随意安装额外程序，还请仔细研究一下kcptun的工作机制，不安装额外程序没有办法使用一些功能，如果对socks5不放心，请自行更改配置文件，结合$$使用
