### ISSUE TITLE
README 里面能加个client 用的配置json范例吗?

### ISSUE THREAD

**Issue by fcying** [clangcn/kcp-server#27]
服务器端安装后倒是自动生成了一份...

客户端 不知道怎么用啊

**Comment by clangcn** [comment]
在服务器端的/usr/local/kcp-server/client.json这有一个，还有参考https://github.com/xtaci/kcptun/releases/tag/v20160830
这个

**Comment by fcying** [comment]
没发现服务器上就有生成一个...已经 用上了...感谢~~
