### ISSUE TITLE
kcp-server间歇性退出，能否用 supervisor 监控并实现自动重启呢？

### ISSUE THREAD

**Issue by choicky** [clangcn/kcp-server#31]
每隔几天，运行 /etc/init.d/kcp-server status 就会发现 kcp-server 退出了。

尝试过把  /etc/init.d/kcp-server start 写到 supervisor 的监控里，但失败了。

如打算使用 supervisor 监控，应当如何写呢？

**Comment by Leask** [comment]
理论上这样写就行了，但是你需要在服务里面先禁用它：

[program:kcp-server]
command=/usr/local/kcp-server
directory=/usr/local/
autostart=true
autorestart=true
user=root
stderr_logfile=/var/log/kcp-server.stderr.log
stdout_logfile=/var/log/kcp-server.stdout.log

**Comment by choicky** [comment]
@Leask 
我在你的基础上调整了一下，现在正常了。

[program:kcp-server]主要调整路径，并增加配置文件
command=/usr/local/kcp-server/kcp-server -c /usr/local/kcp-server/server-kcptun.json
directory=/usr/local/kcp-server

另，这进程依赖于一个后台进程 socks5，所以我增加了一个[program:socks5]
command=/usr/local/kcp-server/socks5 127.0.0.1:port

现在能用了，只是还不够完美。例如把[program:socks5]的端口写死了，而实际上配置文件server-kcptun.json已经定义了 "target": "127.0.0.1:port"

**Comment by Leask** [comment]
👍

**Comment by floydchenv** [comment]
为什么会在刚启动的时候就启动了5-7个server-kcp-amd64进程，而且时间长了内存就会爆炸

**Comment by clangcn** [comment]
crontab里加一条，每天凌晨1点执行重启：
0 1 * * * /etc/init.d/kcp-server restart

**Comment by ddqp** [comment]
mark
