### ISSUE TITLE
Socks5 proxy sever binary

### ISSUE THREAD

**Issue by menghang** [clangcn/kcp-server#35]
Would you please provide some detailed information about the socks5 proxy server binary used in kcp-server? Is it an open-source software? Could you share official website of it? Thank you very much.

**Comment by clangcn** [comment]
build for https://github.com/kcptunsocks/kcptun/tree/router

**Comment by jannson** [comment]
Maybe only one file to support sock5 server here:
https://github.com/kcptunsocks/kcptun/blob/router/socks5/main.go
