### ISSUE TITLE
请问如何在手机上使用？

### ISSUE THREAD

**Issue by chenxiccc** [clangcn/kcp-server#38]
请问如何在手机（iOS）上使用，是否有iOS上的客户端？比如shadowrockets该如何配置？
如果iOS上没有客户端，那么kcpserver是否内置了ss或者socks代理，该在shadowrocket上如何配置呢？

我现在是用kcptun 给 ss加速。路由上使用ss并配置kcp的客户端参数。手机在外面时是使用shadowrocket连接无kcp加速的ss。
在考虑直接用clang的kcpserver，因为只需要部署一个kcpserver就好了，不需要再分别部署ss+kcp，不过不知道kcpserver如何在手机上使用。还是说想在手机上使用，并不能靠kcpserver解决，还是要单独部署个ss服务端。

**Comment by alwayswdc** [comment]
手机上有一个整合ShadowsocksR和KCP的版本，安卓名字叫影梭Android 客户端魔改版，iso上你自己找找吧

**Comment by clangcn** [comment]
kcp-server不支持手机
