### ISSUE TITLE
有没有针对osx的？也写一个呗

### ISSUE THREAD

**Issue by zhanhb** [clangcn/kcp-server#43]

**Comment by clangcn** [comment]
服务端还是客户端？

**Comment by zhanhb** [comment]
客户端，服务器应该没有人用mac搭的吧？

**Comment by clangcn** [comment]
https://github.com/clangcn/kcp-server/blob/master/client_latest/client_darwin_amd64
这个就是

**Comment by zhanhb** [comment]
我知道二进制文件是有的，我本来意思是说写一个脚本，用于生产mac上的kcptun客户端的自启动服务。
