### ISSUE TITLE
想问下 Google AMP 的页面该怎么访问

### ISSUE THREAD

**Issue by yangxuan8282** [clangcn/kcp-server#44]
即使开了 ss 和 kcp 也访问不了 AMP 的页面，都是 404
手机访问 reddit 或其它几个网站的话好多页面都看不了了
而且 AMP 没有地方关

**Comment by clangcn** [comment]
来个网址测试下

**Comment by yangxuan8282** [comment]
https://www.google.com/amp/blog.alexellis.io/getting-started-with-docker-on-raspberry-pi/amp/
Clang <notifications@github.com>于2017年1月20日 周五下午3:25写道：

**Comment by yangxuan8282** [comment]
后来又试了一下，在 iOS ( Wingy, shadowsocks ) 和 Openwrt ( shadowsocks + kcp ) 的网络下无法访问 AMP 页面
android ( 用 shadowsocks 客户端 ) 可以访问

AMP 是针对移动设备的

**Comment by yangxuan8282** [comment]
后来可以访问 amp 页面了，好像是自己 ios 用的梯子的问题
