### ISSUE TITLE
About latest and beta

### ISSUE THREAD

**Issue by poyih** [clangcn/kcp-server#5]
Use koolshare.cn's one-click script install is the latest version or beta version? And how to update for the future new version? Thanks.

**Comment by jannson** [comment]
The script support updating itself and updating kcptun to lastest version. use
./install-kcp-server.sh update 
to update it to latest version

**Comment by jannson** [comment]
好吧，原来项目中加了 beta 测试。

**Comment by clangcn** [comment]
请原谅我不会英文，用中文回复，用脚本./install-kcp-server.sh update更新为稳定版本，如果想体验beta版，请手动下载相应的beta目录中的程序覆盖你的程序就行，暂时没有beta版的一键脚本，不过一条wget命令就能搞定，这个应该不难。

**Comment by poyih** [comment]
Thanks for your response.
