### ISSUE TITLE
老师：每次重启机器，kcp-server is stopped！！如何解决

### ISSUE THREAD

**Issue by becapital** [clangcn/kcp-server#50]
每次重启机器，kcp-server is stopped！！！如何解决。谢谢。
速度真的很快，太棒

**Comment by becapital** [comment]
目前机器重启就显示:kcpserver is stopped....但是sock5运行的。谢谢老师

**Comment by becapital** [comment]
最近升级到kcptun 20180305...
socks5和kcpserver都会经常发生stopped....只能restart解决。。。。
老师怎么修复？

**Comment by becapital** [comment]
"sndwnd": 128,貌似参数改为128号很多？？？原来是1024

**Comment by becapital** [comment]
还是会stopped.........郁闷

**Comment by becapital** [comment]
貌似20171201版本没有此问题,如何恢复选择安装此版本？

**Comment by clangcn** [comment]
手动替换一下应该就行吧，这个都停更了
