### ISSUE TITLE
客户端内存泄漏？

### ISSUE THREAD

**Issue by sarielKings** [clangcn/kcp-server#6]
```
这个不知道在kcptun那边提，还是kcp-server这边，既然是这里下载，在这里提吧。
```

client_linux_amd64有严重的内存泄漏问题？（不确定？），表现症状是，当下载一直持续，内存使用一直涨，当耗尽客户端进程会被杀死。
![default](https://cloud.githubusercontent.com/assets/16360320/16898833/5d331496-4c1d-11e6-9b63-7392ac6ed227.png)

**Comment by jannson** [comment]
请用原版的 kcptun 试试。
golang 是自动垃圾回收的，按理应该不会泄漏。
如果原版也有问题的话，在原作者提。这里只是搬运工。
