### ISSUE TITLE
Why there's only binary file?

### ISSUE THREAD

**Issue by kmahyyg** [clangcn/kcp-server#7]
I'm so sorry.
We all know because of some reasons of china policy, so i have to see the source code so that i can use your software.
And also Github is a Open-Source Community.Right?

**Comment by loveuall** [comment]
https://github.com/loveuall/kcptun

**Comment by clangcn** [comment]
这里只是个一键安装脚本，编译的是
https://github.com/loveuall/kcptun
这里的源码。

kcptun项目源码在
https://github.com/xtaci/kcptun

**Comment by buaazp** [comment]
我看了一下，这个https://github.com/loveuall/kcptun 是改版kcptun，增加了个-c选项，连fork都没做，不知道为何要用他这个版本，原版的很多优化都没法同步过去。

如果是为了他所集成的sock5代理，完全可以找一个专门的http/sock代理程序一起打包呀，kcptun原版不集成本来就是让使用者自己选择target吧。

既然你是一键安装脚本，肯定应该基于原版kcptun来搞吧，这个改版半路弃坑了岂不是你这个项目也要悲剧？

**Comment by loveuall** [comment]
已经统一在项目readme 里回答了楼上的问题：
https://github.com/loveuall/kcptun/blob/master/README.md

原版本的很多优化没加上？还请具体指名有哪些？最核心的通信在 kcp-go，并且这个项目同步的是 9天前的代码，最近没有特别明显的性能优化的更新，所以我也没有急着同步。

楼上不用担心项目悲剧，因为代码都开放了，要不维护，自然也会有新人维护，大不了作者自己上。

**Comment by buaazp** [comment]
@loveuall 你这激动个啥劲，又不是要挑你的不是，你辛辛苦苦做的集成当然值得表扬，我是纯粹从维护复杂角度讨论这个【一键集成包】的设计。
1. 改别人代码最好走fork，不然会跟主干分之越走越远，到后面很难再同步origin的变更，这你没意见吧？我看你的项目没走fork，提出担忧，也是常识反应而已。当然你要是勤奋不断地自己做同步，我自然是欢迎的。
2. 我随便看了一下，[这个commit](https://github.com/xtaci/kcptun/commit/bf2abf14e7691acce291504d6dd52a9327036689) 你就没同步吧，以后这种细小的commit越来越多，你每天都翻origin的commit然后应用的你的项目里是很麻烦的，一般过不了多久你就弃坑了。如果走fork一个rebase master基本就完事了。

我自己给很多项目贡献过代码，提出来问题只是想让项目更好用，没别的意思，@clangcn 你同意就改，不同意就不改，高兴就好。

**Comment by loveuall** [comment]
你可以比较下代码，配置部分是要共用的，必须得提供一个 common 的文件夹来处理。同时多用户部分也要改代码，导致这些细节无法很好的与 master 分支合并一块。然后就是去掉了 -t 选项，与主 master 分支也不一样。这些因素都导致不会像你说的，只需要 rebase master就基本完事了，基本上都会冲突。

你提出问题，我回答你，并且回答了其它人好多篇，我并没有使用过激的词汇吧。

**Comment by buaazp** [comment]
无法rebase显然是你设计的问题，只要想兼容，事先设计好，完全是可以做到大部分origin变更都能通过rebase来解决。
本来非fork的代码我是不想看的，为了对比区别刚刚去看了一遍，你这代码真是不咋地，说实话就算你弃坑了估计都没人愿意接手继续维护。
具体的问题我已经给你开issue了：https://github.com/loveuall/kcptun/issues/1

**Comment by clangcn** [comment]
@buaazp 我其实只是个搬运工，我不会写代码，只能凑活的写个shell脚本，方便和我一样的小白可以自行安装。这个版本之所以编译loveuall/kcptun这个项目，是为了在路由器设备上使用。

**Comment by loveuall** [comment]
之前的分支已经不用了，现在服务器端完全用原作者的代码就行，不再需要我项目的代码。

如果是路由器的话，可以用下面的分支支持透明代理：
https://github.com/loveuall/kcptun/tree/router

还有一个好消息是，作者项目的代码已经支持 json 格式了。
