### ISSUE TITLE
start failed in centos 6

### ISSUE THREAD

**Issue by twhc** [clangcn/kcp-server#9]
2016-07-21 15:42:03 (39.5 MB/s) - `/etc/init.d/kcp-server' saved [4679/4679]
###### 
# Manager kcp-server v1.1 for CentOS/Debian/Ubuntu (32bit/64bit)
# Intro: http://koolshare.cn/forum-72-1.html
# Author: Clang
###### 

Starting kcp-server.../etc/init.d/kcp-server: line 63:  1297 Trace/breakpoint trap   ${BIN} -c ${CONFIGFILE} > ${LOGFILE} 2>&1
start failed
./install-kcp-server.sh: line 264:  1303 Trace/breakpoint trap   ${str_program_dir}/kcp-server --version

**Comment by r03r03** [comment]
我也是有一台VPS一直是这样，试着更换了几个不同的系统，结果都是这个start failed。以前老版本的时候，是可以顺利一键安装的。

**Comment by whour** [comment]
我的Centos6也是如此，没能启动成功。

**Comment by clangcn** [comment]
方便的话留下邮箱，我把我qq号发给你，远程帮你看看

**Comment by whour** [comment]
刚下载了最新releases，还是提示错误，无法启动
`
Starting kcp-server.../etc/init.d/kcp-server: line 63:  1108 Trace/breakpoint trap   ${BIN} -c ${CONFIGFILE} > ${LOGFILE} 2>&1
start failed
`

**Comment by clangcn** [comment]
@bubbless 留下邮箱，我把qq号发给你，远程帮你看一下

**Comment by luq885** [comment]
有同样的问题，其他两个vps安装运行都正常，另外一个就出这个错误，Centos 6 x86

**Comment by twhc** [comment]
**出现在搬瓦工的vps上，虚拟机512m内存**
qq：11-666-3574.。。

**Comment by whour** [comment]
搬瓦工 Centos x86 编译最新版的kcptun，运行一直是 opening stop。
